services:
  server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - data:/data
    environment:
      - MYSQL_HOST=database
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
      - RESOURCE_DATA_DIR=/data
    depends_on:
      database:
        condition: service_healthy
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pexample"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  data:
